//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autos
    {
        public int IdAuto { get; set; }
        public int Año { get; set; }
        public string Color { get; set; }
        public Nullable<int> Kilometraje { get; set; }
        public Nullable<int> NumeroPuertas { get; set; }
        public string Transmisión { get; set; }
        public string Combustible { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdModelo { get; set; }
        public Nullable<int> IdVersion { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Version Version { get; set; }
    }
}
